import type { Metadata } from "next";
import { Marcellus , Montserrat} from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import CursorProvider from "@/components/ui/cursorcontext";

const marcellus = Marcellus({ 
  subsets: ["latin"] ,
  weight:['400'],
  variable:'--font-marcellus',
});
const montserrat = Montserrat({ 
  subsets: ["latin"] ,
  weight:['100','200','300','400','500','600','700','800','900'],
  variable:'--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${marcellus.variable} ${montserrat.variable} overflow-hidden`}>
        <CursorProvider>
        <Header/>
        {children}
        </CursorProvider>
        </body>
    </html>
  );
}
